In [8]:
import sqlite3
import pandas as pd
from pathlib import Path

BASE = Path().resolve().parent
conn = sqlite3.connect(BASE / "data" / "db" / "bluestock_mf.db")

def run_query(title, sql):
    print(f"\n{'='*55}")
    print(f" {title}")
    print('='*55)
    df = pd.read_sql_query(sql, conn)
    print(df.to_string(index=False))
    return df

In [9]:
run_query("Q1: Top 5 funds by AUM", """
    SELECT scheme_name, fund_house, aum_crore
    FROM fact_performance
    ORDER BY aum_crore DESC
    LIMIT 5
""")

=======================================================
 Q1: Top 5 funds by AUM
=======================================================
                                          scheme_name        fund_house  aum_crore
Mirae Asset Emerging Bluechip Fund - Regular - Growth    Mirae Asset MF      49046
        Kotak Emerging Equity Fund - Regular - Growth Kotak Mahindra MF      47469
       Nippon India Small Cap Fund - Regular - Growth   Nippon India MF      43630
           DSP Top 100 Equity Fund - Regular - Growth   DSP Mutual Fund      41828
                  UTI Mid Cap Fund - Regular - Growth   UTI Mutual Fund      41728

,scheme_name,fund_house,aum_crore
0,Mirae Asset Emerging Bluechip Fund - Regular -...,Mirae Asset MF,49046
1,Kotak Emerging Equity Fund - Regular - Growth,Kotak Mahindra MF,47469
2,Nippon India Small Cap Fund - Regular - Growth,Nippon India MF,43630
3,DSP Top 100 Equity Fund - Regular - Growth,DSP Mutual Fund,41828
4,UTI Mid Cap Fund - Regular - Growth,UTI Mutual Fund,41728

In [10]:
run_query("Q2: Average NAV per month (sample — SBI Bluechip)", """
    SELECT amfi_code,
           STRFTIME('%Y-%m', date) AS month,
           ROUND(AVG(nav), 4) AS avg_nav
    FROM fact_nav
    WHERE amfi_code = 119551
    GROUP BY amfi_code, month
    ORDER BY month
""")

=======================================================
 Q2: Average NAV per month (sample — SBI Bluechip)
=======================================================
 amfi_code   month  avg_nav
    119551 2022-01  55.0884
    119551 2022-02  52.4818
    119551 2022-03  50.8359
    119551 2022-04  52.0363
    119551 2022-05  51.8883
    119551 2022-06  52.6814
    119551 2022-07  52.6937
    119551 2022-08  53.7734
    119551 2022-09  56.5458
    119551 2022-10  57.8837
    119551 2022-11  60.8502
    119551 2022-12  61.3497
    119551 2023-01  60.2697
    119551 2023-02  61.1346
    119551 2023-03  64.5890
    119551 2023-04  67.3590
    119551 2023-05  66.2099
    119551 2023-06  69.6245
    119551 2023-07  70.8259
    119551 2023-08  73.7556
    119551 2023-09  74.0329
    119551 2023-10  71.2114
    119551 2023-11  72.8890
    119551 2023-12  72.1944
    119551 2024-01  68.3420
    119551 2024-02  66.8681
    119551 2024-03  67.3711
    119551 2024-04  69.2138
    119551 2024-05  72.8798
    119551 2024-06  73.6522
    119551 2024-07  73.6517
    119551 2024-08  72.6288
    119551 2024-09  73.0433
    119551 2024-10  72.5913
    119551 2024-11  71.3889
    119551 2024-12  74.3899
    119551 2025-01  77.0333
    119551 2025-02  78.7644
    119551 2025-03  81.9696
    119551 2025-04  84.1216
    119551 2025-05  88.9376
    119551 2025-06  99.5813
    119551 2025-07 106.1640
    119551 2025-08 104.9913
    119551 2025-09 110.5374
    119551 2025-10 107.1190
    119551 2025-11 113.7120
    119551 2025-12 121.1552
    119551 2026-01 126.8675
    119551 2026-02 124.6292
    119551 2026-03 129.9909
    119551 2026-04 137.7345
    119551 2026-05 148.4039

    amfi_code    month   avg_nav
0      119551  2022-01   55.0884
1      119551  2022-02   52.4818
2      119551  2022-03   50.8359
3      119551  2022-04   52.0363
4      119551  2022-05   51.8883
5      119551  2022-06   52.6814
6      119551  2022-07   52.6937
7      119551  2022-08   53.7734
8      119551  2022-09   56.5458
9      119551  2022-10   57.8837
10     119551  2022-11   60.8502
11     119551  2022-12   61.3497
12     119551  2023-01   60.2697
13     119551  2023-02   61.1346
14     119551  2023-03   64.5890
15     119551  2023-04   67.3590
16     119551  2023-05   66.2099
17     119551  2023-06   69.6245
18     119551  2023-07   70.8259
19     119551  2023-08   73.7556
20     119551  2023-09   74.0329
21     119551  2023-10   71.2114
22     119551  2023-11   72.8890
23     119551  2023-12   72.1944
24     119551  2024-01   68.3420
25     119551  2024-02   66.8681
26     119551  2024-03   67.3711
27     119551  2024-04   69.2138
28     119551  2024-05   72.8798
29     119551  2024-06   73.6522
30     119551  2024-07   73.6517
31     119551  2024-08   72.6288
32     119551  2024-09   73.0433
33     119551  2024-10   72.5913
34     119551  2024-11   71.3889
35     119551  2024-12   74.3899
36     119551  2025-01   77.0333
37     119551  2025-02   78.7644
38     119551  2025-03   81.9696
39     119551  2025-04   84.1216
40     119551  2025-05   88.9376
41     119551  2025-06   99.5813
42     119551  2025-07  106.1640
43     119551  2025-08  104.9913
44     119551  2025-09  110.5374
45     119551  2025-10  107.1190
46     119551  2025-11  113.7120
47     119551  2025-12  121.1552
48     119551  2026-01  126.8675
49     119551  2026-02  124.6292
50     119551  2026-03  129.9909
51     119551  2026-04  137.7345
52     119551  2026-05  148.4039

In [11]:
run_query("Q3: SIP inflow YoY growth", """
    SELECT month,
           sip_inflow_crore,
           ROUND(yoy_growth_pct, 2) AS yoy_growth_pct
    FROM fact_sip_industry
    WHERE yoy_growth_pct IS NOT NULL
    ORDER BY month
""")

=======================================================
 Q3: SIP inflow YoY growth
=======================================================
     month  sip_inflow_crore  yoy_growth_pct
2023-01-01             13856           20.31
2023-02-01             13687           19.66
2023-03-01             14276           15.80
2023-04-01             14749           24.33
2023-05-01             14749           20.05
2023-06-01             14734           20.02
2023-07-01             15245           25.58
2023-08-01             15814           24.58
2023-09-01             16042           23.63
2023-10-01             16928           29.82
2023-11-01             17073           28.31
2023-12-01             17610           29.74
2024-01-01             18838           35.96
2024-02-01             19187           40.18
2024-03-01             20371           42.69
2024-04-01             20371           38.12
2024-05-01             21262           44.16
2024-06-01             21262           44.31
2024-07-01             23332           53.05
2024-08-01             23547           48.90
2024-09-01             24509           52.78
2024-10-01             25323           49.59
2024-11-01             25320           48.30
2024-12-01             26459           50.25
2025-01-01             26400           40.14
2025-02-01             25999           35.50
2025-03-01             25926           27.27
2025-04-01             26632           30.73
2025-05-01             26688           25.52
2025-06-01             27274           28.28
2025-07-01             28464           22.00
2025-08-01             28265           20.04
2025-09-01             29361           19.80
2025-10-01             29529           16.61
2025-11-01             30200           19.27
2025-12-01             31002           17.17

         month  sip_inflow_crore  yoy_growth_pct
0   2023-01-01             13856           20.31
1   2023-02-01             13687           19.66
2   2023-03-01             14276           15.80
3   2023-04-01             14749           24.33
4   2023-05-01             14749           20.05
5   2023-06-01             14734           20.02
6   2023-07-01             15245           25.58
7   2023-08-01             15814           24.58
8   2023-09-01             16042           23.63
9   2023-10-01             16928           29.82
10  2023-11-01             17073           28.31
11  2023-12-01             17610           29.74
12  2024-01-01             18838           35.96
13  2024-02-01             19187           40.18
14  2024-03-01             20371           42.69
15  2024-04-01             20371           38.12
16  2024-05-01             21262           44.16
17  2024-06-01             21262           44.31
18  2024-07-01             23332           53.05
19  2024-08-01             23547           48.90
20  2024-09-01             24509           52.78
21  2024-10-01             25323           49.59
22  2024-11-01             25320           48.30
23  2024-12-01             26459           50.25
24  2025-01-01             26400           40.14
25  2025-02-01             25999           35.50
26  2025-03-01             25926           27.27
27  2025-04-01             26632           30.73
28  2025-05-01             26688           25.52
29  2025-06-01             27274           28.28
30  2025-07-01             28464           22.00
31  2025-08-01             28265           20.04
32  2025-09-01             29361           19.80
33  2025-10-01             29529           16.61
34  2025-11-01             30200           19.27
35  2025-12-01             31002           17.17

In [12]:
run_query("Q4: Total transactions by state", """
    SELECT state,
           COUNT(*) AS total_transactions,
           SUM(amount_inr) AS total_amount_inr,
           ROUND(AVG(amount_inr), 2) AS avg_amount_inr
    FROM fact_transactions
    GROUP BY state
    ORDER BY total_amount_inr DESC
""")

=======================================================
 Q4: Total transactions by state
=======================================================
         state  total_transactions  total_amount_inr  avg_amount_inr
        Punjab                2965         315780459       106502.68
    Tamil Nadu                2806         315177237       112322.61
Madhya Pradesh                2931         308312493       105190.21
     Rajasthan                2577         298645822       115888.95
       Gujarat                2780         298358940       107323.36
   West Bengal                2748         297182514       108145.02
     Telangana                2718         290219284       106776.78
         Delhi                2677         289633404       108193.28
 Uttar Pradesh                2695         285368873       105888.26
       Haryana                2736         279634354       102205.54
     Karnataka                2621         273753570       104446.23
   Maharashtra                2524         269513480       106780.30

             state  total_transactions  total_amount_inr  avg_amount_inr
0           Punjab                2965         315780459       106502.68
1       Tamil Nadu                2806         315177237       112322.61
2   Madhya Pradesh                2931         308312493       105190.21
3        Rajasthan                2577         298645822       115888.95
4          Gujarat                2780         298358940       107323.36
5      West Bengal                2748         297182514       108145.02
6        Telangana                2718         290219284       106776.78
7            Delhi                2677         289633404       108193.28
8    Uttar Pradesh                2695         285368873       105888.26
9          Haryana                2736         279634354       102205.54
10       Karnataka                2621         273753570       104446.23
11     Maharashtra                2524         269513480       106780.30

In [13]:
run_query("Q5: Funds with expense_ratio < 1%", """
    SELECT scheme_name, fund_house, expense_ratio_pct, plan
    FROM dim_fund
    WHERE expense_ratio_pct < 1.0
    ORDER BY expense_ratio_pct ASC
""")

=======================================================
 Q5: Funds with expense_ratio < 1%
=======================================================
                                         scheme_name               fund_house  expense_ratio_pct    plan
Nippon India Gilt Securities Fund - Regular - Growth          Nippon India MF               0.55 Regular
        HDFC Short Term Debt Fund - Regular - Growth         HDFC Mutual Fund               0.56 Regular
                Kotak Liquid Fund - Regular - Growth        Kotak Mahindra MF               0.60 Regular
            SBI Bluechip Fund - Direct Plan - Growth          SBI Mutual Fund               0.66  Direct
           SBI Small Cap Fund - Direct Plan - Growth          SBI Mutual Fund               0.72  Direct
       Nippon India Large Cap Fund - Direct - Growth          Nippon India MF               0.72  Direct
            ICICI Pru Liquid Fund - Regular - Growth      ICICI Prudential MF               0.74 Regular
                Axis Bluechip Fund - Direct - Growth         Axis Mutual Fund               0.75  Direct
        SBI Magnum Gilt Fund - Regular Plan - Growth          SBI Mutual Fund               0.77 Regular
   HDFC Mid-Cap Opportunities Fund - Direct - Growth         HDFC Mutual Fund               0.78  Direct
                 ABSL Liquid Fund - Regular - Growth Aditya Birla Sun Life MF               0.79 Regular
           ICICI Pru Bluechip Fund - Direct - Growth      ICICI Prudential MF               0.80  Direct
                      Nippon India ETF Nifty 50 BeES          Nippon India MF               0.89  Direct
            HDFC Top 100 Fund - Direct Plan - Growth         HDFC Mutual Fund               0.92  Direct

,scheme_name,fund_house,expense_ratio_pct,plan
0,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,0.55,Regular
1,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,0.56,Regular
2,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,0.60,Regular
3,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,0.66,Direct
4,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,0.72,Direct
5,Nippon India Large Cap Fund - Direct - Growth,Nippon India MF,0.72,Direct
6,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,0.74,Regular
7,Axis Bluechip Fund - Direct - Growth,Axis Mutual Fund,0.75,Direct
8,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,0.77,Regular
9,HDFC Mid-Cap Opportunities Fund - Direct - Growth,HDFC Mutual Fund,0.78,Direct
10,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,0.79,Regular
11,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,0.80,Direct
12,Nippon India ETF Nifty 50 BeES,Nippon India MF,0.89,Direct
13,HDFC Top 100 Fund - Direct Plan - Growth,HDFC Mutual Fund,0.92,Direct

In [14]:
run_query("Q6: Top 5 funds by Sharpe ratio", """
    SELECT scheme_name, fund_house, sharpe_ratio,
           return_3yr_pct, risk_grade
    FROM fact_performance
    ORDER BY sharpe_ratio DESC
    LIMIT 5
""")

=======================================================
 Q6: Top 5 funds by Sharpe ratio
=======================================================
                                 scheme_name               fund_house  sharpe_ratio  return_3yr_pct risk_grade
    ICICI Pru Liquid Fund - Regular - Growth      ICICI Prudential MF          7.68            7.68        Low
        Kotak Liquid Fund - Regular - Growth        Kotak Mahindra MF          6.18            6.18        Low
         ABSL Liquid Fund - Regular - Growth Aditya Birla Sun Life MF          5.14            5.14        Low
HDFC Short Term Debt Fund - Regular - Growth         HDFC Mutual Fund          1.84            7.37        Low
SBI Magnum Gilt Fund - Regular Plan - Growth          SBI Mutual Fund          1.52            6.07        Low

,scheme_name,fund_house,sharpe_ratio,return_3yr_pct,risk_grade
0,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,7.68,7.68,Low
1,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,6.18,6.18,Low
2,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,5.14,5.14,Low
3,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,1.84,7.37,Low
4,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,1.52,6.07,Low

In [15]:
run_query("Q7: AUM growth by fund house per year", """
    SELECT fund_house,
           STRFTIME('%Y', date) AS year,
           ROUND(AVG(aum_lakh_crore), 2) AS avg_aum_lakh_crore
    FROM fact_aum
    GROUP BY fund_house, year
    ORDER BY fund_house, year
""")

=======================================================
 Q7: AUM growth by fund house per year
=======================================================
              fund_house year  avg_aum_lakh_crore
Aditya Birla Sun Life MF 2022                2.81
Aditya Birla Sun Life MF 2023                2.92
Aditya Birla Sun Life MF 2024                3.62
Aditya Birla Sun Life MF 2025                4.22
        Axis Mutual Fund 2022                2.45
        Axis Mutual Fund 2023                2.50
        Axis Mutual Fund 2024                2.90
        Axis Mutual Fund 2025                3.30
         DSP Mutual Fund 2022                1.11
         DSP Mutual Fund 2023                1.23
         DSP Mutual Fund 2024                1.72
         DSP Mutual Fund 2025                2.13
        HDFC Mutual Fund 2022                4.40
        HDFC Mutual Fund 2023                4.92
        HDFC Mutual Fund 2024                7.14
        HDFC Mutual Fund 2025                8.63
     ICICI Prudential MF 2022                4.77
     ICICI Prudential MF 2023                5.45
     ICICI Prudential MF 2024                7.65
     ICICI Prudential MF 2025                9.77
       Kotak Mahindra MF 2022                2.71
       Kotak Mahindra MF 2023                3.07
       Kotak Mahindra MF 2024                4.25
       Kotak Mahindra MF 2025                5.36
          Mirae Asset MF 2022                1.06
          Mirae Asset MF 2023                1.29
          Mirae Asset MF 2024                1.92
          Mirae Asset MF 2025                2.58
         Nippon India MF 2022                2.74
         Nippon India MF 2023                3.17
         Nippon India MF 2024                4.89
         Nippon India MF 2025                6.30
         SBI Mutual Fund 2022                6.17
         SBI Mutual Fund 2023                7.81
         SBI Mutual Fund 2024               10.65
         SBI Mutual Fund 2025               12.50
         UTI Mutual Fund 2022                2.31
         UTI Mutual Fund 2023                2.52
         UTI Mutual Fund 2024                3.17
         UTI Mutual Fund 2025                3.82

                  fund_house  year  avg_aum_lakh_crore
0   Aditya Birla Sun Life MF  2022                2.81
1   Aditya Birla Sun Life MF  2023                2.92
2   Aditya Birla Sun Life MF  2024                3.62
3   Aditya Birla Sun Life MF  2025                4.22
4           Axis Mutual Fund  2022                2.45
5           Axis Mutual Fund  2023                2.50
6           Axis Mutual Fund  2024                2.90
7           Axis Mutual Fund  2025                3.30
8            DSP Mutual Fund  2022                1.11
9            DSP Mutual Fund  2023                1.23
10           DSP Mutual Fund  2024                1.72
11           DSP Mutual Fund  2025                2.13
12          HDFC Mutual Fund  2022                4.40
13          HDFC Mutual Fund  2023                4.92
14          HDFC Mutual Fund  2024                7.14
15          HDFC Mutual Fund  2025                8.63
16       ICICI Prudential MF  2022                4.77
17       ICICI Prudential MF  2023                5.45
18       ICICI Prudential MF  2024                7.65
19       ICICI Prudential MF  2025                9.77
20         Kotak Mahindra MF  2022                2.71
21         Kotak Mahindra MF  2023                3.07
22         Kotak Mahindra MF  2024                4.25
23         Kotak Mahindra MF  2025                5.36
24            Mirae Asset MF  2022                1.06
25            Mirae Asset MF  2023                1.29
26            Mirae Asset MF  2024                1.92
27            Mirae Asset MF  2025                2.58
28           Nippon India MF  2022                2.74
29           Nippon India MF  2023                3.17
30           Nippon India MF  2024                4.89
31           Nippon India MF  2025                6.30
32           SBI Mutual Fund  2022                6.17
33           SBI Mutual Fund  2023                7.81
34           SBI Mutual Fund  2024               10.65
35           SBI Mutual Fund  2025               12.50
36           UTI Mutual Fund  2022                2.31
37           UTI Mutual Fund  2023                2.52
38           UTI Mutual Fund  2024                3.17
39           UTI Mutual Fund  2025                3.82

In [16]:
run_query("Q8: Transaction split — SIP vs Lumpsum vs Redemption", """
    SELECT transaction_type,
           COUNT(*) AS count,
           SUM(amount_inr) AS total_amount,
           ROUND(AVG(amount_inr), 2) AS avg_amount
    FROM fact_transactions
    GROUP BY transaction_type
""")

=======================================================
 Q8: Transaction split — SIP vs Lumpsum vs Redemption
=======================================================
transaction_type  count  total_amount  avg_amount
         Lumpsum   8095    2059821448   254456.02
      Redemption   4967    1244525491   250558.79
             Sip  19716     217233491    11018.13

  transaction_type  count  total_amount  avg_amount
0          Lumpsum   8095    2059821448   254456.02
1       Redemption   4967    1244525491   250558.79
2              Sip  19716     217233491    11018.13

In [17]:
run_query("Q9: Top sectors by total portfolio weight", """
    SELECT sector,
           ROUND(SUM(weight_pct), 2) AS total_weight_pct,
           COUNT(DISTINCT amfi_code) AS num_funds
    FROM fact_portfolio
    GROUP BY sector
    ORDER BY total_weight_pct DESC
    LIMIT 10
""")

=======================================================
 Q9: Top sectors by total portfolio weight
=======================================================
        sector  total_weight_pct  num_funds
       Banking            652.26         30
            IT            455.47         27
        Pharma            407.45         22
    Automobile            323.65         26
     Utilities            265.54         19
          FMCG            229.11         19
Infrastructure            192.16         18
   Diversified            169.23         14
       Telecom            145.62         15
Consumer Goods            127.61          9

           sector  total_weight_pct  num_funds
0         Banking            652.26         30
1              IT            455.47         27
2          Pharma            407.45         22
3      Automobile            323.65         26
4       Utilities            265.54         19
5            FMCG            229.11         19
6  Infrastructure            192.16         18
7     Diversified            169.23         14
8         Telecom            145.62         15
9  Consumer Goods            127.61          9

In [18]:
run_query("Q10: Best performing funds vs benchmark", """
    SELECT p.scheme_name,
           p.return_1yr_pct,
           p.benchmark_3yr_pct,
           p.alpha,
           p.sharpe_ratio,
           f.benchmark
    FROM fact_performance p
    JOIN dim_fund f ON p.amfi_code = f.amfi_code
    ORDER BY p.return_1yr_pct DESC
    LIMIT 10
""")

=======================================================
 Q10: Best performing funds vs benchmark
=======================================================
                                      scheme_name  return_1yr_pct  benchmark_3yr_pct  alpha  sharpe_ratio            benchmark
           ABSL Small Cap Fund - Regular - Growth           24.93              20.54   1.84          0.90 BSE 250 SmallCap TRI
       SBI Small Cap Fund - Regular Plan - Growth           24.56              22.16   1.23          0.94 BSE 250 SmallCap TRI
           Axis Small Cap Fund - Regular - Growth           21.97              20.47   0.51          0.84 BSE 250 SmallCap TRI
   Nippon India Small Cap Fund - Regular - Growth           21.30              19.35   0.80          0.81 BSE 250 SmallCap TRI
        SBI Small Cap Fund - Direct Plan - Growth           20.59              22.01   1.13          0.93 BSE 250 SmallCap TRI
            DSP Small Cap Fund - Regular - Growth           20.20              19.39   0.69          0.80 BSE 250 SmallCap TRI
HDFC Mid-Cap Opportunities Fund - Direct - Growth           19.98              14.39   0.90          0.80 NIFTY Midcap 150 TRI
            UTI Flexi Cap Fund - Regular - Growth           17.43              13.55   1.79          0.96        NIFTY 500 TRI
    Kotak Emerging Equity Fund - Regular - Growth           17.12              16.32   1.91          0.96 NIFTY Midcap 150 TRI
ICICI Pru Value Discovery Fund - Regular - Growth           16.67              14.21   0.55          0.98        NIFTY 500 TRI

,scheme_name,return_1yr_pct,benchmark_3yr_pct,alpha,sharpe_ratio,benchmark
0,ABSL Small Cap Fund - Regular - Growth,24.93,20.54,1.84,0.90,BSE 250 SmallCap TRI
1,SBI Small Cap Fund - Regular Plan - Growth,24.56,22.16,1.23,0.94,BSE 250 SmallCap TRI
2,Axis Small Cap Fund - Regular - Growth,21.97,20.47,0.51,0.84,BSE 250 SmallCap TRI
3,Nippon India Small Cap Fund - Regular - Growth,21.30,19.35,0.80,0.81,BSE 250 SmallCap TRI
4,SBI Small Cap Fund - Direct Plan - Growth,20.59,22.01,1.13,0.93,BSE 250 SmallCap TRI
5,DSP Small Cap Fund - Regular - Growth,20.20,19.39,0.69,0.80,BSE 250 SmallCap TRI
6,HDFC Mid-Cap Opportunities Fund - Direct - Growth,19.98,14.39,0.90,0.80,NIFTY Midcap 150 TRI
7,UTI Flexi Cap Fund - Regular - Growth,17.43,13.55,1.79,0.96,NIFTY 500 TRI
8,Kotak Emerging Equity Fund - Regular - Growth,17.12,16.32,1.91,0.96,NIFTY Midcap 150 TRI
9,ICICI Pru Value Discovery Fund - Regular - Growth,16.67,14.21,0.55,0.98,NIFTY 500 TRI

In [19]:
conn.close()
print("All 10 queries complete ✓")

All 10 queries complete ✓